# Generated by Django 5.2 on 2025-06-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoagil', '0002_alter_historiaclinica_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='preco',
        ),
        migrations.AddField(
            model_name='servico',
            name='aparelho_apoio',
            field=models.CharField(default='sem aparelho', max_length=200),
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo_servicos',
            field=models.CharField(default='sem código', max_length=50),
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo_servicos_secundarios',
            field=models.CharField(default='sem código', max_length=50),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao_servicos',
            field=models.TextField(default='sem descrição'),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao_servicos_secundario',
            field=models.TextField(default='sem descrição'),
        ),
        migrations.AddField(
            model_name='servico',
            name='material_usado',
            field=models.CharField(default='sem material', max_length=200),
        ),
        migrations.AddField(
            model_name='servico',
            name='observacoes',
            field=models.TextField(default='sem observações'),
        ),
    ]
