# Generated by Django 5.2 on 2025-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoagil', '0003_remove_servico_descricao_remove_servico_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='codigo_servicos_secundarios',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
