# Generated by Django 5.2 on 2025-06-07 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoagil', '0004_alter_servico_codigo_servicos_secundarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_inclusao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
