# Generated by Django 5.2 on 2025-06-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontoagil', '0005_servico_data_inclusao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='codigo_servicos_secundarios',
            new_name='codigo_servicos_secundario',
        ),
    ]
