# Generated by Django 5.2.1 on 2025-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/servicos'),
        ),
    ]
