# Generated by Django 5.2 on 2025-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('nome_mae', models.CharField(blank=True, max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200)),
                ('nome_contato_familiar', models.CharField(blank=True, max_length=200)),
                ('grau_parentesco', models.CharField(blank=True, max_length=100)),
                ('telefone_contato_familiar', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
