# Generated by Django 5.2.1 on 2025-06-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField()),
                ('codigo_servicos', models.CharField(max_length=50)),
                ('material_usado', models.CharField(max_length=255)),
                ('descricao_servicos', models.TextField()),
                ('codigo_servicos_secundarios', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_servicos_secundarios', models.TextField(blank=True, null=True)),
                ('aparelho_apoio', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
